# azure-pipelines.yml
# Build and Push Docker Image to Docker Hub
# Place this file at the root of your GitHub repository

trigger:
  - main   # runs on pushes to main branch

variables:
  IMAGE_NAME: "example-voting-app-result"
  TAG: "$(Build.BuildId)"   # unique build number tag

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    pool:
      name: azureagent   # must match your self-hosted agent pool exactly
    steps:

    # Step 1: Checkout repository
    - task: Checkout@1
      displayName: Checkout Repository

    # Step 2: Build and push Docker image
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        containerRegistry: docker-hub    # your Docker Hub service connection name
        repository: akyldocker25/$(IMAGE_NAME)   # replace with your Docker Hub username
        dockerfile: result/Dockerfile
        buildContext: result
        tags: |
          latest
          $(TAG)
        platforms: linux/amd64,linux/arm64,linux/arm/v7

