trigger:
- main

resources:
- repo: self

variables:
  IMAGE_NAME: voting-app-azure-dev-result
  TAG: $(Build.BuildId)
  DOCKER_HUB_USERNAME: akyldocker25
  DOCKER_HUB_SERVICE_CONNECTION: docker-hub

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      name: azureagent  # your self-hosted Linux agent

    steps:
    # 1. Checkout repository
    - task: Checkout@1
      displayName: Checkout Repository

    # 2. Install Docker
    - script: |
        echo "Installing Docker..."
        sudo apt-get update
        sudo apt-get install -y docker.io
      displayName: Install Docker

    # 3. Install Docker Buildx (if not already)
    - script: |
        echo "Setting up Docker Buildx..."
        mkdir -p ~/.docker/cli-plugins
        curl -SL https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx
        docker buildx version
      displayName: Install Docker Buildx

    # 4. Add current user to Docker group
    - script: |
        echo "Updating Docker permissions..."
        sudo usermod -aG docker $(whoami)
        newgrp docker
      displayName: Adjust Docker Permissions

    # 5. Docker Hub login
    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: $(DOCKER_HUB_SERVICE_CONNECTION)

    # 6. Build & push multi-platform image
    - script: |
        echo "Building and pushing Docker image..."
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t $(DOCKER_HUB_USERNAME)/$(IMAGE_NAME):$(TAG) \
          -t $(DOCKER_HUB_USERNAME)/$(IMAGE_NAME):latest \
          -f result/Dockerfile result \
          --push
      displayName: Build and Push Docker Image
