trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: voting-app-azure-dev-result
  TAG: $(Build.BuildId)   # Dynamic build ID tag
  DOCKER_HUB_USERNAME: akyldocker25
  DOCKER_HUB_SERVICE_CONNECTION: docker-hub  # Your service connection name

jobs:
  - job: BuildAndPushDocker
    displayName: Build and Push Docker Image to Docker Hub
    pool:
      name: azureagent  # Your self-hosted Linux agent

    steps:
      # 1. Checkout code
      - task: Checkout@1
        displayName: Checkout Repository

      # 2. Install Docker (if needed)
      - script: |
          echo "Installing Docker..."
          sudo apt-get update
          sudo apt-get install -y docker.io
        displayName: Install Docker

      # 3. Update Docker permissions for agent user
      - script: |
          echo "Updating Docker permissions..."
          sudo usermod -aG docker $(whoami)
          newgrp docker
        displayName: Adjust Docker Permissions

      # 4. Login to Docker Hub using service connection
      - task: Docker@2
        displayName: Docker Login
        inputs:
          command: login
          containerRegistry: $(DOCKER_HUB_SERVICE_CONNECTION)

      # 5. Build & push multi-platform Docker image
      - script: |
          echo "Building and pushing Docker image..."
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t $(DOCKER_HUB_USERNAME)/$(IMAGE_NAME):$(TAG) \
            -t $(DOCKER_HUB_USERNAME)/$(IMAGE_NAME):latest \
            -f result/Dockerfile result \
            --push
        displayName: Build and Push Docker Image
