# azure-pipelines.yml
trigger:
  - main

variables:
  IMAGE_NAME: "example-voting-app-result"
  TAG: "$(Build.BuildId)"

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    pool:
      name: azureagent   # your self-hosted agent pool
    steps:

    - task: Checkout@1
      displayName: Checkout Repository

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        containerRegistry: docker-hub   # your Docker Hub service connection name
        repository: akyldocker25/$(IMAGE_NAME)
        dockerfile: result/Dockerfile
        buildContext: result
        tags: |
          latest
          $(TAG)
        platforms: linux/amd64,linux/arm64,linux/arm/v7

