name: Build and Deploy Voting App

on:
  push:
    branches:
      - main
    paths:
      - "result/**"
      - "vote/**"
      - "worker/**"
      - ".github/workflows/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [result, vote, worker] # All three services
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Image Tag
        id: set_tag
        run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t akyldocker25/voting-app-${{ matrix.service }}:${{ steps.set_tag.outputs.tag }} ./${{ matrix.service }}
          docker push akyldocker25/voting-app-${{ matrix.service }}:${{ steps.set_tag.outputs.tag }}

      - name: Update Kubernetes Manifest
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"
          git pull --rebase origin main
          bash scripts/updateK8sManifests.sh akyldocker25/voting-app-${{ matrix.service }} ${{ steps.set_tag.outputs.tag }} ${{ matrix.service }}
          git push https://$GIT_USER:$GIT_TOKEN@github.com/akylgit/voting-app-azure-dev.git HEAD:main
